[project]
name = "vanity-deployer"
version = "0.1.0"
description = "Script generates link to deploy vanity-contract"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pytoniq>=0.1.41",
    "toml>=0.10.2",
]

[dependency-groups]
dev = [
    "ruff>=0.12.3",
]
